name: climlab-courseware
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - xarray
  - metpy
  - cartopy
  - sympy
  - ffmpeg
  - jupyter
  - climlab>=0.7.11  # older versions used a data download and caching strategy that breaks Binder
  - numba>=0.43.1  # older version will hang forever under python 3, https://github.com/brian-rose/climlab/issues/101
  - netcdf4
  - nc-time-axis
  - jupyter-book  # needed to rebuild the book from source
